global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'dashboard'
    file_sd_configs:
      - files:
         - /etc/prometheus/targets/targets.json
        refresh_interval: 10s
